# Generated by Django 5.1.1 on 2024-10-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(default='id', max_length=20)),
                ('productname', models.CharField(default='productname', max_length=20)),
                ('userid', models.CharField(default='userid', max_length=20)),
                ('quantity', models.CharField(max_length=50)),
                ('cart_status', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=10)),
                ('category_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(default='id', max_length=20)),
                ('productname', models.CharField(default='productname', max_length=20)),
                ('userid', models.CharField(default='userid', max_length=20)),
                ('quantity', models.CharField(max_length=50)),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='name', max_length=20)),
                ('productid', models.CharField(default='id', max_length=20)),
                ('username', models.CharField(default='username', max_length=20)),
                ('userid', models.CharField(default='userid', max_length=20)),
                ('reviewdescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(default='id', max_length=20)),
                ('productname', models.CharField(default='productname', max_length=20)),
                ('userid', models.CharField(default='userid', max_length=20)),
                ('wishlist_status', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('house_no', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('number', models.CharField(default='number', max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=20)),
                ('subcategory_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='name', max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(default='size', max_length=10)),
                ('color', models.CharField(default='color', max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.subcategory')),
            ],
        ),
    ]
