# Generated by Django 5.1.1 on 2024-10-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_id',
        ),
    ]
