# Generated by Django 5.1.1 on 2024-10-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confirm_password',
        ),
    ]
