# Generated by Django 5.1.1 on 2024-10-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0004_remove_registration_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
