# Generated by Django 5.1.1 on 2024-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0005_remove_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(max_length=20),
        ),
    ]
