# Generated by Django 5.1.1 on 2024-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0006_alter_category_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.URLField(),
        ),
    ]
