# Generated by Django 5.1.1 on 2024-10-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0007_alter_subcategory_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.URLField(),
        ),
    ]
