# Generated by Django 5.1.1 on 2024-11-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0010_remove_address_userid_address_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='loginId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login'),
        ),
    ]
