# Generated by Django 5.1.1 on 2024-11-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0011_alter_address_loginid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='loginId',
            new_name='login_id',
        ),
    ]
