# Generated by Django 5.1.1 on 2024-11-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0012_rename_loginid_address_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='login_id',
        ),
        migrations.AddField(
            model_name='address',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login'),
        ),
    ]
