# Generated by Django 5.1.1 on 2024-11-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0013_remove_address_login_id_address_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='loginid',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login'),
        ),
    ]
