# Generated by Django 5.1.1 on 2024-11-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0016_address_date_address_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='loginId',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login'),
        ),
    ]
