# Generated by Django 5.1.1 on 2024-11-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0021_remove_address_date_remove_address_loginid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login'),
        ),
    ]
