# Generated by Django 5.1.1 on 2024-11-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0023_remove_address_userid_address_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='login_id',
        ),
        migrations.AddField(
            model_name='address',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopzonee.login'),
        ),
    ]
