# Generated by Django 5.1.1 on 2024-11-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopzonee', '0024_remove_address_login_id_address_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.URLField(),
        ),
    ]
